#!/usr/bin/env bash
# Filename:      grml2iso
# Purpose:       create a multiboot grml ISO using grml2usb
# Authors:       Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -e -o pipefail

# make sure we have the sbin directories in our PATH to find grml2usb ootb
PATH="${PATH}:/sbin:/usr/local/sbin:/usr/sbin"

# adjust variables if necessary through environment {{{
# path to the grml2usb script you'd like to use
[ -n "$GRML2USB" ] || GRML2USB='grml2usb'

if ! which xorriso >/dev/null 2>&1 ; then
  echo "Error: xorriso not found - can not create ISO." >&2
  exit 1
fi
# }}}

# helper stuff {{{
  usage() {
    echo >&2 "Usage: $0 [OPTIONS] -o target.iso source1.iso [source2.iso ...]"
    echo >&2 "
Options:
     -b Boot Params      Additional boot parameters passed to grml2usb
     -c Directory        Copy files from directory to generated ISO
     -f                  Force overwrite of existing target.iso
     -r BootParam        Remove specified boot params.
                         Can be specified multiple times.
     -p <grml2usb param> Add the specified parameter to the grml2usb
                         commandline. For a list of valid parameters have
                         a look at the grml2usb manpage.
                         Can be specified multiple times.
     -s URI              Generate a small ISO file which downloads the squashfs
                         file from the specified URI. Please note that due to
                         restrictions in the bootprocess only IPs are allowed.
                         Supported protocols are: http and ftp
     -t Directory        Directory that should be used for temporary files
                         during build, instead of using a temporary directory
                         created by mktemp(1).

     Examples:
     $0 -s http://192.168.23.42:8000/grml/ -o small.iso grml64-small_2021.07.iso

     Will generate a file small.iso which tries to download the squashfs file from
     http://192.168.23.42:8000/grml/ - the squashfs file is placed in the same
     output directory as the ISO file.
"
    [ -n "$1" ] && exit $1 || exit 1
  }
# }}}

# command line handling {{{
  [[ $# -gt 2 ]] || usage 1

  ISOFILE=''
  DIR=''
  ADD_OPTS=''
  FORCE=''
  URI=''
  typeset -a GRML2USB_OPTS
  while getopts fb:c:o:r:p:s:t: name; do
    case $name in
      o)   ISOFILE="$OPTARG";;
      b)   GRML2USB_OPTS+=(--bootoptions="$OPTARG");;
      c)   DIR="$(readlink -f "$OPTARG")"; [ -n "$DIR" ] || { echo "Could not read $OPTARG - exiting" >&2 ; exit 1 ; } ;;
      f)   FORCE='true';;
      r)   GRML2USB_OPTS+=(--remove-bootoption="$OPTARG");;
      p)   GRML2USB_OPTS+=("$OPTARG");;
      s)   URI="$OPTARG";;
      t)   WRKDIR="$(readlink -f "$OPTARG")";;
      ?)   usage 2;;
    esac
  done

  # test for specified URI
  if [ -n "$URI" ] ; then
    GRML2USB_OPTS+=(--bootoptions="fetch=$URI")
  fi

# make sure -o is specified
  [ -n "$ISOFILE" ] || usage 1

# we don't to override any files by accident
  if [ -e "$ISOFILE" -a ! -n "$FORCE" ]; then
    echo "Error: target file $ISOFILE exists already." >&2
    exit 1
  fi

  if [ ! -z "$DIR" -a ! -d "$DIR" ] ; then
     echo "Error: specified parameter for -c is not a directory" >&2
     exit 1
  fi
# }}}

# we need root permissions for executing grml2usb {{{
  if [[ $(id -u) != 0 ]]; then
    echo >&2 "Error: please run $0 as root."
    exit 1
  fi
# }}}

# check for grml2usb {{{
  if [ ! -x "$(which $GRML2USB)" ] && [ ! -x "$GRML2USB" ] ; then
    echo "Error: Could not find grml2usb executable. Is /usr/sbin missing in PATH?" >&2
    echo "Tip: run GRML2USB=/usr/sbin/grml2usb grml2iso ... as workaround" >&2
    if [ -x "./$GRML2USB" ] ; then
      echo >&2 "If you executed grml2iso from the grml2usb repository use"
      echo >&2 "GRML2USB=./grml2usb $0 $*"
    fi
    exit 1
  fi
# }}}

# variables {{{
  ORIG_DIR="$(pwd)"

# normalise path
  case $ISOFILE in
    /*) ;;
    *) ISOFILE=$ORIG_DIR/$ISOFILE ;;
  esac
# }}}

# ensure to properly set up working directory {{{
  WRKDIR_EXISTED='false'
  if [ -z "$WRKDIR" ] ; then
    WRKDIR="$(mktemp -d)"
  else
    [ -d "$WRKDIR" ] && WRKDIR_EXISTED='true'
  fi

  GRML2USB_OPTS+=(--tmpdir="$WRKDIR")

  rm -rf "$WRKDIR/cddir" "$WRKDIR/grub_tmp"
  mkdir -p "$WRKDIR/cddir"
# }}}}

# execute grml2usb with all ISOs you'd like to install {{{
  # remove all parameters
  shift $(($OPTIND - 1))

  $GRML2USB "${GRML2USB_OPTS[@]}" "$@" "$WRKDIR/cddir"
# }}}

# change to $WRKDIR {{{
  # make sure $WRKDIR is an absolute path, otherwise accessing files
  # in it will fail later in the code path if user provided a
  # relative directory
  WRKDIR=$(realpath $WRKDIR)
  cd "$WRKDIR/cddir"
# }}}

# detect boot method and set up boot arguments {{{
  BOOT_ARGS=""
  USE_ISOLINUX=false
  USE_GRUB=false
  HOST_ARCH="$(uname -m)"

  # Check if syslinux/isolinux files are available
  # On arm64 hosts, prefer GRUB since isohybrid is not available
  if [ -d "$WRKDIR/cddir/boot/syslinux" ] && [ "$HOST_ARCH" != "aarch64" ] ; then
    echo "Found syslinux files, using isolinux for BIOS boot."
    USE_ISOLINUX=true
    mv "$WRKDIR"/cddir/boot/syslinux "$WRKDIR"/cddir/boot/isolinux
    echo "menu label ^Isolinux prompt" > "$WRKDIR"/cddir/boot/isolinux/promptname.cfg
    echo "include hd.cfg" >> "$WRKDIR"/cddir/boot/isolinux/grmlmain.cfg
  elif [ -d "$WRKDIR/cddir/boot/grub" ] ; then
    if [ -d "$WRKDIR/cddir/boot/syslinux" ] ; then
      echo "Found syslinux files, but using GRUB for BIOS boot (running on $HOST_ARCH)."
      rm -rf "$WRKDIR/cddir/boot/syslinux"
    else
      echo "No syslinux files found, using GRUB for BIOS boot."
    fi
    USE_GRUB=true
  else
    echo "Warning: Neither syslinux nor GRUB boot files found." >&2
  fi

  echo "Using xorriso for ISO generation."

  if [ "$USE_ISOLINUX" = "true" ] ; then
    # isolinux-based BIOS boot
    if ! which isohybrid >/dev/null 2>&1 ; then
      echo "Error: isohybrid executable not found (install syslinux/isolinux/syslinux-utils?)." >&2
      exit 1
    fi
    BOOT_ARGS="-no-emul-boot -boot-load-size 4 -boot-info-table -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat"

    if [ -r "${WRKDIR}/cddir/boot/efi.img" ] ; then
      echo "/boot/efi.img found, enabling (U)EFI boot support."
      if ! [ -r /usr/lib/ISOLINUX/isohdpfx.bin ] ; then
        echo "Error: /usr/lib/ISOLINUX/isohdpfx.bin not available, required for xorriso/isohybrid." >&2
        echo "Hint:  make sure isolinux is installed." >&2
        exit 1
      fi
      BOOT_ARGS+=" -eltorito-alt-boot -e boot/efi.img -no-emul-boot"
      BOOT_ARGS+=" -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -isohybrid-gpt-basdat -no-pad"
    fi

  elif [ "$USE_GRUB" = "true" ] ; then
    # GRUB-based BIOS boot
    GRUB_BIOS_AVAILABLE=false

    # Check if source ISO already has GRUB BIOS boot image
    if [ -r "boot/grub/i386-pc/eltorito.img" ] ; then
      echo "Using existing GRUB BIOS boot image from source ISO."
      GRUB_BIOS_AVAILABLE=true
    elif [ -r "boot/grub/i386-pc/cdboot.img" ] ; then
      echo "Using existing GRUB cdboot.img from source ISO."
      cp boot/grub/i386-pc/cdboot.img boot/grub/i386-pc/eltorito.img
      GRUB_BIOS_AVAILABLE=true
    elif [ -d "/usr/lib/grub/i386-pc" ] ; then
      # Try to generate GRUB BIOS boot image (requires i386-pc modules)
      if which grub-mkimage >/dev/null 2>&1 ; then
        echo "Generating GRUB BIOS boot image..."
        mkdir -p boot/grub/i386-pc
        if grub-mkimage -o boot/grub/i386-pc/eltorito.img -O i386-pc-eltorito -p /boot/grub \
            biosdisk iso9660 linux configfile normal search search_fs_file search_label part_msdos part_gpt fat ext2 2>/dev/null ; then
          GRUB_BIOS_AVAILABLE=true
        else
          echo "Warning: Failed to generate GRUB BIOS boot image." >&2
        fi
      fi
    fi

    if [ "$GRUB_BIOS_AVAILABLE" = "true" ] ; then
      # Find GRUB's boot.img for hybrid MBR (check ISO first, then system)
      GRUB_BOOT_IMG=""
      for path in boot/grub/i386-pc/boot.img /usr/lib/grub/i386-pc/boot.img /usr/share/grub/i386-pc/boot.img ; do
        if [ -r "$path" ] ; then
          GRUB_BOOT_IMG="$path"
          break
        fi
      done

      BOOT_ARGS="-no-emul-boot -boot-load-size 4 -boot-info-table -b boot/grub/i386-pc/eltorito.img -c boot/grub/boot.cat"
      BOOT_ARGS+=" --grub2-boot-info"

      if [ -r "${WRKDIR}/cddir/boot/efi.img" ] ; then
        echo "/boot/efi.img found, enabling (U)EFI boot support."
        BOOT_ARGS+=" -eltorito-alt-boot -e boot/efi.img -no-emul-boot"
        if [ -n "$GRUB_BOOT_IMG" ] ; then
          BOOT_ARGS+=" --grub2-mbr $GRUB_BOOT_IMG -isohybrid-gpt-basdat -no-pad"
        else
          echo "Warning: GRUB boot.img not found, ISO may not be hybrid-bootable from USB." >&2
          BOOT_ARGS+=" -no-pad"
        fi
      elif [ -n "$GRUB_BOOT_IMG" ] ; then
        BOOT_ARGS+=" --grub2-mbr $GRUB_BOOT_IMG -no-pad"
      fi
    elif [ -r "${WRKDIR}/cddir/boot/efi.img" ] ; then
      # Fall back to EFI-only boot
      echo "Warning: GRUB i386-pc modules not available, falling back to EFI-only boot." >&2
      echo "Hint: Install grub-pc-bin for BIOS boot support on non-x86 hosts." >&2
      USE_GRUB=false
      BOOT_ARGS="-e boot/efi.img -no-emul-boot -isohybrid-gpt-basdat -no-pad"
    else
      echo "Error: Cannot create bootable ISO - no BIOS or EFI boot method available." >&2
      exit 1
    fi

  else
    # EFI-only boot (e.g., arm64)
    if [ -r "${WRKDIR}/cddir/boot/efi.img" ] ; then
      echo "Using EFI-only boot."
      BOOT_ARGS="-e boot/efi.img -no-emul-boot -isohybrid-gpt-basdat -no-pad"
    else
      echo "Error: No bootable configuration found." >&2
      exit 1
    fi
  fi
# }}}

# adjust ISO for small output if necessary {{{
  if [ -n "$URI" ] ; then
     bootloader_files=$(find . -name "*.cfg" -type f)
     bootloader_files+=" "
     bootloader_files+=$(find . -name "*.lst" -type f)
     output_dir=$(dirname "$ISOFILE")
     for squashfs in $(find . -name *.squashfs) ; do
        media_path="$(dirname "$squashfs")"
        filename="$(basename "$squashfs")"
        target="$output_dir/$filename"
        if [ -f "$target" ] && [ ! -n "$FORCE" ] ; then
           echo >&2 "Warning: $target already exists, and -force not specified, not overwriting"
        else
           mv $squashfs $target
           OUTPUT_FILES+=("$target")
        fi
        sed -i -e "s#^\(^.*$media_path.*\)\($URI\)\(.*$\)#\1$URI/$filename\3#g" $bootloader_files

   done
  fi
# }}}

# copy specified directory to cd {{{
  if [ -n "$DIR" ] ; then
     echo >&2 "Copying ${DIR} to generated ISO"
     for param in GRML_NAME VERSION RELEASENAME DATE SHORT_NAME \
         VERSION BOOTID RELEASE_INFO ; do
       EXCLUDE_PARAM="$EXCLUDE_PARAM --exclude **%${param}%**"
     done
     rsync -a ${DIR}/ $EXCLUDE_PARAM .
  fi

  # adjust files from overlay directory
  for GRML_VERSION_FILE in $(find . -name grml-version) ; do
    GRML_NAME=$(awk '{print $1}' "$GRML_VERSION_FILE")
    VERSION=$(awk '{print $2}' "$GRML_VERSION_FILE")
    RELEASENAME=$(sed 's/.*- \(.*\).*\[.*/\1/' "$GRML_VERSION_FILE")
    DATE=$(sed 's/.*\[\(.*\)].*/\1/' "$GRML_VERSION_FILE")
    SHORT_NAME="$(echo $GRML_NAME | tr -d ',./;\- ')"
    RELEASE_INFO="$GRML_NAME $VERSION - $RELEASENAME"
    BOOTID=$(cat conf/bootid.txt)

    for param in GRML_NAME VERSION RELEASENAME DATE SHORT_NAME \
        RELEASE_INFO BOOTID  ; do
      value="$(eval echo '$'"$param")"

      # copy parameterized files from the overlay directory
      for file in $(find ${DIR} -name "*%$param%*") ; do
        file=${file##$DIR/}
        target_dir="$(dirname ${file})"
        mkdir -p "$target_dir" || true
        cp -r ${DIR}/${file} ./${target_dir}/"$(basename ${file/\%${param}\%/$value})"
      done

      # adjust config files
      for file in ./boot/isolinux/*.cfg ./boot/isolinux/*.msg \
        ./boot/grub/*.cfg ; do
        sed -i "s/%$param%/$value/g" ${file} 2>/dev/null || true
      done
    done
  done
# }}}

# generate the CD/DVD ISO {{{
  xorriso -as mkisofs -V 'grml-multiboot' -l -r -J $BOOT_ARGS \
    -o "$ISOFILE" .
# }}}

# cleanup {{{
  cd "$ORIG_DIR"
  sync
  rm -rf "$WRKDIR/cddir" "$WRKDIR/grub_tmp"
  [[ $WRKDIR_EXISTED = 'false' ]] && rmdir "$WRKDIR"
  echo "Generated $ISOFILE"
  if [ -n "$URI" ] ; then
     echo "
Information:
==============
You requested to generate a small ISO image. Your generated
ISO image $ISOFILE does _not_ contain the squashfs files from
the source ISO images.

You have to provide the extracted squashfs files under $URI.

ISO image: $ISOFILE
Squashfs files: ${OUTPUT_FILES[@]}
URI: $URI
"
  fi
# }}}

## EOF #########################################################################
# vim:foldmethod=marker ts=2 ft=sh ai expandtab tw=80 sw=2
