#!/usr/bin/env bash
# Filename:      grml2iso
# Purpose:       create a multiboot grml ISO using grml2usb
# Authors:       Michael Prokop <mika@grml.org>,
#                Thorsten Glaser <tg@mirbsd.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

# define function getfilesize before "set -e" {{{
  if stat --help >/dev/null 2>&1; then
    getfilesize='stat -c %s'        # GNU stat
  else
    getfilesize='stat -f %z'        # BSD stat
  fi
# }}}

# adjust variables if necessary through environment {{{
# path to the grml2usb script you'd like to use
  [ -n "$GRML2USB" ] || GRML2USB='grml2usb'
# work directory for creating the filesystem
  [ -n "$WRKDIR" ]   || WRKDIR='/tmp/grml2iso.tmp'
# support mkisofs as well as genisoimage
  if which mkisofs >/dev/null 2>&1; then
    MKISOFS='mkisofs'
  elif which genisoimage >/dev/null 2>&1; then
    MKISOFS='genisoimage'
  else
    echo >&2 "Error: neither mkisofs nor genisoimage available - can not create ISO."
    exit 1
fi
# }}}

# helper stuff {{{
  set -e

  usage() {
    echo >&2 "Usage: $0 [OPTIONS] -o target.iso source1.iso [source2.iso ...]"
    echo >&2 "
Options:
     -b Boot Params      Additional boot parameters passed to grml2usb
     -c Directory        Copy files from directory to generated iso
     -f                  Force overwrite of existing target.iso
     -r BootParam        Remove specified boot params.
                         Could be specfied multiple times.
     -p <grml2usb param> Add the specified parameter to the grml2usb
                         commandline. For a list of valid parameters have
                         a look at the grml2usb manpage.
                         Could be specfied multiple times.
     -s URI              Generate a small iso file which downloads the squashfs
                         file from the specified URI. Please note that due to
                         restrictions in the bootprocess only IPs are allowed.
                         Supported protocols are: http and ftp

     Examples:
     $0 -s http://192.168.23.42:8000/grml/ -o small.iso grml64_2010.12.iso

     Will generate a file small.iso which tries to download the squashfs file from
     http://192.168.23.42:8000/grml/ The squashfs file is located in the output
     directory as the iso file.
"
    [ -n "$1" ] && exit $1 || exit 1
  }
# }}}

# command line handling {{{
  [[ $# -gt 2 ]] || usage 1

  ISOFILE=''
  DIR=''
  ADD_OPTS=''
  FORCE=''
  URI=''
  typeset -a GRML2USB_OPTS
  while getopts fb:c:o:r:p:s: name; do
    case $name in
      o)   ISOFILE="$OPTARG";;
      b)   GRML2USB_OPTS+=(--bootoptions="$OPTARG");;
      c)   DIR="$OPTARG";;
      f)   FORCE='true';;
      r)   GRML2USB_OPTS+=(--remove-bootoption="$OPTARG");;
      p)   GRML2USB_OPTS+=("$OPTARG");;
      s)   URI="$OPTARG";;
      ?)   usage 2;;
    esac
  done
  # test for specified URI
  if [ -n "$URI" ] ; then
    GRML2USB_OPTS+=(--bootoptions="fetch=$URI")
  fi

# make sure -o is specified
  [ -n "$ISOFILE" ] || usage 1

# we don't to override any files by accident
  if [ -e "$ISOFILE" -a ! -n "$FORCE" ]; then
    echo "Error: target file $ISOFILE exists already." >&2
    exit 1
  fi

  if [ ! -z "$DIR" -a ! -d "$DIR" ] ; then
     echo "Error: specified parameter for -c is not a directory" >&2
     exit 1
  fi
# }}}

# we need root permissions for executing grml2usb {{{
  if [[ $(id -u) != 0 ]]; then
    echo >&2 "Error: please run $0 as root."
    exit 1
  fi
# }}}

# check for grml2usb {{{
  if [ ! -x "$(which $GRML2USB)" ] || [ ! -x "$GRML2USB" ] ; then
    echo >&2 "Error: Could not find grml2usb"
    if [ -x "./$GRML2USB" ] ; then
      echo >&2 "If you executed grml2iso from the grml2usb repository use"
      echo >&2 "GRML2USB=./grml2usb $0 $*"
    fi
    exit 1
  fi
# }}}

# variables {{{
  ORIG_DIR="$(pwd)"
  # note: grub-pc_1.96+20090603-1 seems to be b0rken
  GRUB_VERSION="grub-pc_1.96+20080724-16"

# normalise path
  case $ISOFILE in
    /*) ;;
    *) ISOFILE=$ORIG_DIR/$ISOFILE ;;
  esac
# }}}

# create necessary stuff under WRKDIR {{{
  [ -d "$WRKDIR" ] && WRKDIR_EXISTED='true' || WRKDIR_EXISTED='false'
  rm -rf "$WRKDIR/cddir" "$WRKDIR/grub_tmp"
  mkdir -p "$WRKDIR/cddir"
# }}}}

# execute grml2usb with all ISOs you'd like to install {{{
  # remove all parameters
  shift $(($OPTIND - 1))

  $GRML2USB "${GRML2USB_OPTS[@]}" "$@" "$WRKDIR/cddir"
# }}}


# move syslinux to isolinux {{{
  mv "$WRKDIR"/cddir/boot/syslinux "$WRKDIR"/cddir/boot/isolinux

  cd "$WRKDIR/cddir"
  echo "menu label ^Isolinux prompt" > boot/isolinux/promptname.cfg
  echo "include hd.cfg" >> boot/isolinux/grmlmain.cfg
# }}}

# adjust iso for small output if necessary [{{
  if [ -n "$URI" ] ; then
     bootloader_files=$(find . -name "*.cfg" -type f)
     bootloader_files+=" "
     bootloader_files+=$(find . -name "*.lst" -type f)
     output_dir=$(dirname "$ISOFILE")
     for squashfs in $(find . -name *.squashfs) ; do
        media_path="$(dirname "$squashfs")"
        filename="$(basename "$squashfs")"
        target="$output_dir/$filename"
        if [ -f "$target" ] && [ ! -n "$FORCE" ] ; then
           echo >&2 "Warning: $target already exists, and -force not specified, not overwriting"
        else
           mv $squashfs $target
           OUTPUT_FILES+=("$target")
        fi
        sed -i -e "s#^\(^.*$media_path.*\)\($URI\)\(.*$\)#\1$URI/$filename\3#g" $bootloader_files

   done
  fi
# }}}

# copy specified directory to cd {{{
  if [ -n "$DIR" ] ; then
     echo >&2 "Copying ${DIR} to generated iso"
     rsync -a ${DIR}/ .
  fi

# }}}

# generate the CD/DVD ISO {{{
  $MKISOFS -V 'grml-multiboot' -l -r -J -no-pad \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat \
    -o "$ISOFILE" .
# }}}

# pad the output ISO to multiples of 256 KiB for partition table support {{{
  siz=$($getfilesize "$ISOFILE")
  cyls=$(echo "$siz / 512 / 32 / 16 + 1" | bc)  # C=$cyls H=16 S=32
  ofs=$(echo "$cyls * 16 * 32 * 512 - 1" | bc)  # padding offset (size - 1)
  dd if=/dev/zero bs=1 count=1 seek=$ofs of="$ISOFILE" 2>/dev/null
# }}}


# cleanup {{{
  cd "$ORIG_DIR"
  sync
  rm -rf "$WRKDIR/cddir" "$WRKDIR/grub_tmp"
  [[ $WRKDIR_EXISTED = 'false' ]] && rmdir "$WRKDIR"
  echo "Generated $ISOFILE"
  if [ -n "$URI" ] ; then
     echo "
Information:
==============
You requested to generate a small iso image. Your generated
iso image $ISOFILE does _not_ contain the squashfs files from
the source iso images.

You have to provide the extracted squashfs files under $URI.

ISO image: $ISOFILE
Squashfs files: ${OUTPUT_FILES[@]}
URI: $URI
"
  fi
# }}}

## EOF #########################################################################
# vim:foldmethod=marker ts=2 ft=sh ai expandtab tw=80 sw=3
